sonar.projectKey=FastPix_html5-player-sdk
sonar.organization=fastpix

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=html5-player-sdk
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Files/folders excluded from analysis (no issues raised on these).
sonar.exclusions=demo/**,src/utils/backup.ts

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8